---
env:
  es6: true
  node: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
extends:
  - airbnb-base
  - prettier
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:jest/recommended
  - plugin:jest/style
settings:
  settings:
    import/resolver:
      node:
        extensions:
          - .js
          - .jsx
          - .ts
          - .tsx
    import/parsers:
      '@typescript-eslint/parser':
        - .ts
        - .tsx
rules:
  '@typescript-eslint/no-floating-promises': ['error']
  no-shadow: off
  linebreak-style: off
  no-console: warn
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/no-default-export: error
  import/prefer-default-export: off
  import/no-unresolved: off
  import/no-extraneous-dependencies: off
  prettier/prettier:
    - error
    - endOfLine: auto
  jest/prefer-strict-equal: error
  jest/no-conditional-expect: off
