service: gamblingkingsbackend

plugins:
  - serverless-webpack
  #######################################
  # Uncomment this for local dev only
  #######################################
  - serverless-offline
  - serverless-dynamodb-local

custom:
  webpack:
    includeModules: true
  serverless-offline:
    useChildProcesses: true
  #######################################
  # Uncomment this for local dev only
  #######################################
  dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2

  websocketsApiName: mahjong-websocket
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'execute-api:ManageConnections'
      Resource:
        - 'arn:aws:execute-api:*:*:**/@connections/*'
    - Effect: Allow
      Action:
        - 'dynamodb:PutItem'
        - 'dynamodb:GetItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:BatchGetItem'
        - 'dynamodb:BatchWriteItem'
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
      Resource:
        - Fn::GetAtt: [ConnectionsTable, Arn]
        - Fn::GetAtt: [GamesTable, Arn]
        - Fn::Join:
            - '/'
            - - Fn::GetAtt: [ConnectionsTable, Arn]
              - '*'
        - Fn::Join:
            - '/'
            - - Fn::GetAtt: [GamesTable, Arn]
              - '*'

  # you can define service wide environment variables here
  environment:
    CONNECTIONS_TABLE:
      Ref: ConnectionsTable
    GAMES_TABLE:
      Ref: GamesTable
    API_REGION: '${self:provider.region}'
    NODE_PATH: /opt/nodejs:/opt/nodejs/node12/node_modules:/opt/nodejs/node_modules:/var/runtime/node_modules:/var/runtime:/var/task

package:
  individually: true

functions:
  onConnect:
    handler: src/functions/onConnect.handler
    events:
      - websocket: $connect
  onDisconnect:
    handler: src/functions/onDisconnect.handler
    events:
      - websocket: $disconnect
  defaultHandler:
    handler: src/functions/defaultMessage.handler
    events:
      - websocket: $default
  setUsername:
    handler: src/functions/onSetUsername.handler
    events:
      - websocket: SET_USERNAME
  getAllUsers:
    handler: src/functions/onGetAllUsers.handler
    events:
      - websocket: GET_ALL_USERS
  createGame:
    handler: src/functions/onCreateGame.handler
    events:
      - websocket: CREATE_GAME
  getAllGames:
    handler: src/functions/onGetAllGames.handler
    events:
      - websocket: GET_ALL_GAMES
  sendMessage:
    handler: src/functions/onSendMessage.handler
    events:
      - websocket: SEND_MESSAGE
  joinGame:
    handler: src/functions/onJoinGame.handler
    events:
      - websocket: JOIN_GAME
  leaveGame:
    handler: src/functions/onLeaveGame.handler
    events:
      - websocket: LEAVE_GAME

# you can add CloudFormation resource templates here
resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ConnectionsTable
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    GamesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: GamesTable
        AttributeDefinitions:
          - AttributeName: gameId
            AttributeType: S
        KeySchema:
          - AttributeName: gameId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
