service: gamblingkingsbackend

plugins:
  - serverless-webpack
  #######################################
  # Uncomment this for local dev only
  #######################################
  - serverless-offline
  - serverless-dynamodb-local

custom:
  webpack:
    includeModules: true
  serverless-offline:
    useChildProcesses: true
  #######################################
  # Uncomment this for local dev only
  #######################################
  dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2

  websocketsApiName: mahjong-websocket
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'execute-api:ManageConnections'
      Resource:
        - 'arn:aws:execute-api:*:*:**/@connections/*'
    - Effect: Allow
      Action:
        - 'dynamodb:PutItem'
        - 'dynamodb:GetItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:BatchGetItem'
        - 'dynamodb:BatchWriteItem'
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
      Resource:
        - Fn::GetAtt: [Connections, Arn]
        - Fn::GetAtt: [Games, Arn]
        - Fn::GetAtt: [GameState, Arn]
        - Fn::Join:
            - '/'
            - - Fn::GetAtt: [Connections, Arn]
              - '*'
        - Fn::Join:
            - '/'
            - - Fn::GetAtt: [Games, Arn]
              - '*'
        - Fn::Join:
            - '/'
            - - Fn::GetAtt: [GameState, Arn]
              - '*'

  # you can define service wide environment variables here
  environment:
    CONNECTIONS_TABLE:
      Ref: Connections
    GAMES_TABLE:
      Ref: Games
    GAME_STATE_TABLE:
      Ref: GameState
    API_REGION: '${self:provider.region}'
    NODE_PATH: /opt/nodejs:/opt/nodejs/node12/node_modules:/opt/nodejs/node_modules:/var/runtime/node_modules:/var/runtime:/var/task

package:
  individually: true

functions:
  # Default handler
  defaultHandler:
    handler: src/functions/defaultMessage.handler
    events:
      - websocket: $default
  # Connection handlers
  onConnect:
    handler: src/functions/connection/onConnect.handler
    events:
      - websocket: $connect
  onDisconnect:
    handler: src/functions/connection/onDisconnect.handler
    events:
      - websocket: $disconnect
  onSetUsername:
    handler: src/functions/connection/onSetUsername.handler
    events:
      - websocket: SET_USERNAME
  # Lobby handlers
  onCreateGame:
    handler: src/functions/lobby/onCreateGame.handler
    events:
      - websocket: CREATE_GAME
  onGetAllUsers:
    handler: src/functions/lobby/onGetAllUsers.handler
    events:
      - websocket: GET_ALL_USERS
  onGetAllGames:
    handler: src/functions/lobby/onGetAllGames.handler
    events:
      - websocket: GET_ALL_GAMES
  onSendMessage:
    handler: src/functions/lobby/onSendMessage.handler
    events:
      - websocket: SEND_MESSAGE
  onJoinGame:
    handler: src/functions/lobby/onJoinGame.handler
    events:
      - websocket: JOIN_GAME
  onLeaveGame:
    handler: src/functions/lobby/onLeaveGame.handler
    events:
      - websocket: LEAVE_GAME
  onStartGame:
    handler: src/functions/lobby/onStartGame.handler
    events:
      - websocket: START_GAME
  # Game handlers
  onGamePageLoad:
    handler: src/functions/game/onGamePageLoad.handler
    events:
      - websocket: GAME_PAGE_LOAD
  onDrawTile:
    handler: src/functions/game/onDrawTile.handler
    events:
      - websocket: DRAW_TILE
  onPlayTile:
    handler: src/functions/game/onPlayTile.handler
    events:
      - websocket: PLAY_TILE

# you can add CloudFormation resource templates here
resources:
  Resources:
    Connections:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Connections
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    Games:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Games
        AttributeDefinitions:
          - AttributeName: gameId
            AttributeType: S
        KeySchema:
          - AttributeName: gameId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    GameState:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: GameState
        AttributeDefinitions:
          - AttributeName: gameId
            AttributeType: S
        KeySchema:
          - AttributeName: gameId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
