name: CD

on:
  # push:
    # branches: [master]
  pull_request:
    branches: [master]

jobs:
  cd:
    # cd job depends on ci
    needs: lint-format-test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      # Install serverless
      - name: Install serverless
        run: yarn global add serverless

      # Deploy to aws
      - name: Deploy
        run: yarn run prod-start
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2

      # Send slack notification
      # Docs: https://action-slack.netlify.app/
      - name: Notify Slack
        uses: 8398a7/action-slack@v3.6.1
        with:
          # Fields
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
          # With Parameters
          channel: '#ci-cd'
          username: GamblingKings-CD-Bot
          author_name: ${{ github.actor }}
          status: ${{ job.status }}
          emoji_icon: ':mahjong:'
          mention: here
          if_mention: failure,cancelled
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
        if: always() # Pick up events even if the job fails or is canceled.
