name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint-format-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      # Caching
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore from cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Install dependencies
      - name: Install Packages
        run: yarn install

      # Linting with ESLint
      - name: Lint
        run: yarn lint

      # Checking format with Prettier
      - name: Check format
        run: yarn format:check

      # Running tests with Jest
      - name: Test
        run: |
          yarn global add codecov
          export CODECOV_TOKEN="${{ secrets.CODECOV_TOKEN_BACKEND }}"
          yarn test

      # Send slack notification
      # Docs: https://action-slack.netlify.app/
      - name: Notify Slack
        uses: 8398a7/action-slack@v3.6.1
        with:
          # Fields
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
          # With Parameters
          channel: '#ci-cd'
          username: GamblingKings-CI-Bot
          author_name: ${{ github.actor }}
          status: ${{ job.status }}
          mention: here
          if_mention: failure,cancelled
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
        if: always() # Pick up events even if the job fails or is canceled.
