name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Linting with ESLint
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install Packages
        run: yarn install
      - name: Lint
        run: yarn lint

  # Checking format with Prettier
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn
      - run: yarn prettier . --check

  # Running tests with Jest
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12', '13']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install codecov
        run: yarn global add codecov
      - name: Install Packages
        run: yarn install
      - name: Test
        run: yarn test

  # Send workflow result via slack notification to the ci-cd channel
  slack-notification:
    runs-on: ubuntu-latest
    needs: [lint, format, test]

    env:
      SLACK_CHANNEL: ci-cd
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_ICON: https://avatars2.githubusercontent.com/u/44036562?s=400&v=4
      SLACK_USERNAME: CI Bot
      SLACK_MESSAGE_TEMPLATE: <https://github.com/${{github.repository}}/pull/${{github.event.pull_request.number}} | Link to PR ${{github.event.pull_request.number}}>

    steps:
      - uses: actions/checkout@v1

      - uses: rtCamp/action-slack-notify@v2.0.2
        name: Slack Success Notification
        if: success()
        env:
          SLACK_TITLE: Success Workflow Message
          SLACK_COLOR: '#1E824C'
          SLACK_MESSAGE: Success ☀️  `${{ env.SLACK_MESSAGE_TEMPLATE }}`

      - uses: rtCamp/action-slack-notify@v2.0.2
        name: Slack Failure Notification
        if: failure()
        env:
          SLACK_TITLE: Failed Workflow Message
          SLACK_COLOR: '#F83535'
          SLACK_MESSAGE: Build Failed 🌧️  `${{ env.SLACK_MESSAGE_TEMPLATE }}`

      - uses: rtCamp/action-slack-notify@v2.0.2
        name: Slack Stopped Notification
        if: cancelled()
        env:
          SLACK_TITLE: Cancelled Workflow Message
          SLACK_COLOR: '#ADADAD'
          SLACK_MESSAGE: Build Stopped ✋🏻  `${{ env.SLACK_MESSAGE_TEMPLATE }}`
